name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Archive files
      run: |
        tar -czf project.tar.gz *

    - name: Copy tarball via scp
      run: |
        scp -o StrictHostKeyChecking=no project.tar.gz ubuntu@ec2-13-126-198-226.ap-south-1.compute.amazonaws.com:/srv/nestjs-deploy

    - name: SSH and deploy
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-126-198-226.ap-south-1.compute.amazonaws.com << 'EOF'
          cd /srv/nestjs-deploy
          tar -xzf project.tar.gz
          rm project.tar.gz
          npm install
          pm2 restart nestjs-app || pm2 start npm --name "nestjs-app" -- run start
          pm2 save
        EOF
